if(!file.exists("./data")){dir.create("./data")}
fileUrl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl,destfile="./data/restaurants.csv", method="curl")
restData <- read.csv("./data/restaurants.csv")
# show the top n lines of the data ...
head(restData, n=3)
# show the last n lines of the data ...
tail(restData, n=3)
# Get a summary of the data ...
summary(restData)
# More information ...
str(restData)
# Get some quantiles ...
quantile(restData$councilDistrict, na.rm=TRUE)
# Get some quantiles with probs
quantile(restData$councilDistrict, probs=c(0.5,0.75,0.9))
# Make a table of one variable ...
table(restData$zipCode, useNA="ifany")
# Make a table of two variables ...
table(restData$councilDistrict, restData$zipCode)
# Check for missing values ...
sum(is.na(restData$councilDistrict))
any(is.na(restData$councilDistrict))
# Check for incorrect values ...
all(restData$zipCode > 0)
# Row and Column sums ...
colSums(is.na(restData))
all(colSums(is.na(restData)) ==0)
# Values with specific characteristics ...
table(restData$zipCode %in% c("21212"))
table(restData$zipCode %in% c("21212", "21213"))
# Get the rows that meets above ...
restData[restData$zipCode %in% c("21212", "21213"),]
# Cross tabs ...
data("UCBAdmissions")
DF = as.data.frame(UCBAdmissions)
summary(DF)
xt <- xtabs(Freq ~ Gender + Admit, data=DF)
xt
# Size of data set ...
fakeData <- rnorm(1e5)
object.size(fakeData)
print(object.size(fakeData), units="Mb")
